version: '3'
services:
  slackbot:
    image: okwrtdsh/slackbot:latest
    volumes:
      - ./app:/app
    environment:
      - DEFAULT_REPLY="Sorry but I didn't understand you"
      - SLACK_API_TOKEN="YOUR_API_TOKEN"
